// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// runXEM
void runXEM(S4 reference);
RcppExport SEXP amisbanana_runXEM(SEXP referenceSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type reference(referenceSEXP);
    runXEM(reference);
    return R_NilValue;
END_RCPP
}
// rbanana
arma::Mat<double> rbanana(const int n, const int d, const double b);
RcppExport SEXP amisbanana_rbanana(SEXP nSEXP, SEXP dSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type d(dSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    __result = Rcpp::wrap(rbanana(n, d, b));
    return __result;
END_RCPP
}
// dbanana
arma::Col<double> dbanana(arma::Mat<double>& x, const double& b);
RcppExport SEXP amisbanana_dbanana(SEXP xSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::Mat<double>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    __result = Rcpp::wrap(dbanana(x, b));
    return __result;
END_RCPP
}
// computedensities
void computedensities(S4 reference, const double b);
RcppExport SEXP amisbanana_computedensities(SEXP referenceSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const double >::type b(bSEXP);
    computedensities(reference, b);
    return R_NilValue;
END_RCPP
}
// computedmixture
void computedmixture(S4 pop, S4 param, int n);
RcppExport SEXP amisbanana_computedmixture(SEXP popSEXP, SEXP paramSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type pop(popSEXP);
    Rcpp::traits::input_parameter< S4 >::type param(paramSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    computedmixture(pop, param, n);
    return R_NilValue;
END_RCPP
}
// dlogistic
arma::Col<double> dlogistic(arma::Mat<double>& x, arma::Col<double>& s);
RcppExport SEXP amisbanana_dlogistic(SEXP xSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::Mat<double>& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::Col<double>& >::type s(sSEXP);
    __result = Rcpp::wrap(dlogistic(x, s));
    return __result;
END_RCPP
}
