# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runXEM <- function(reference) {
    invisible(.Call('amisbanana_runXEM', PACKAGE = 'amisbanana', reference))
}

rbanana <- function(n, d, b) {
    .Call('amisbanana_rbanana', PACKAGE = 'amisbanana', n, d, b)
}

dbanana <- function(x, b) {
    .Call('amisbanana_dbanana', PACKAGE = 'amisbanana', x, b)
}

computedensities <- function(reference, b) {
    invisible(.Call('amisbanana_computedensities', PACKAGE = 'amisbanana', reference, b))
}

computedmixture <- function(pop, param, n) {
    invisible(.Call('amisbanana_computedmixture', PACKAGE = 'amisbanana', pop, param, n))
}

dlogistic <- function(x, s) {
    .Call('amisbanana_dlogistic', PACKAGE = 'amisbanana', x, s)
}

